### ISSUE TITLE
Provide a way to limit access to potentially dangerous tokens

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/token_filter#12] opened 2022-10-28 20:48 UTC
Because many users with different levels of access use the same text formats, there should be a way to limit use of this feature to specific user roles, without needing to limit use of the whole text filter to those roles (which can cause other issues for sites).

Our particular concern is that tokens can be used to reveal Private Information (PI) or Personally Identifiable Information (PII) by using something like `[user:mail]`. To complicate matters, chained tokens can also route back to PI or PII by using something like `[node:author:mail].

Ideas: 
* Add additional permissions for who can use the filters, regardless of which format they are on
* Add settings to limit tokens to a particular type (removing all user tokens from the token tree, even as child/chained tokens)

**Comment by jenlampton** [comment] 2022-10-28 20:50
@argiepiano I know you have a lot of experience with tokens, do you think it would be possible (or, realistic) to alter out all the user-based tokens from this particular instance? Or should we look for alternate solutions?

**Comment by argiepiano** [comment] 2022-10-28 22:45
I think the most straightforward approach (suggested some time ago by @yorkshire-pudding) is to use a similar approach to the "Limit allowed HTML tags" filter but in reverse: entering strings (separated by spaces) that should not be allowed as part of a token to be fulfilled.

For example, you would enter specific text like 'user' or 'author:mail', and the filter would remove the whole token that contains that text, regardless of where in the token that text appears. You can get quite granular by entering chains (e.g. filtering out all 'mail' token occurrences may not be desirable, but 'author:mail' may be more specific).

Currently `token_scan()` uses regex to produce an array of all tokens in a given text. We could use a similar regex to expunge any tokens that contain those strings from the text before sending that to token filter.  

As for allowing different levels of access - that could be done in the configuration of the filter itself, perhaps by having individual textfields for each role in the site?

**Comment by bugfolder** [comment] 2022-10-29 02:21
Things get interesting when people have multiple roles. With permissions, the policy is, "if any of the user's roles have the permission, the user gets the permission." 

If we're consistent about that behavior with this model of denial—the most privileged role wins out—the corresponding policy would be "If any of the user's roles does NOT deny a particular token string, the user can see the token rendered." So if the user has Roles A and B, and A denies only [node:author:mail] and B denies only [node:author:name], then the user would get to see both tokens, since A gets to see the latter and B gets to see the former.

That might be a little confusing, so would need clear explanation in the settings.

Also, the default behavior of Token module is that if a token is unrecognized, it's passed through unaltered. So this might mean that while a privileged user could see "This content was created by bugfolder", a less-privileged user would see "This content was created by [node:author:name]". This might seem to the less-privileged user that there's something wrong with the rendering, not that it's doing what it's supposed to.

**Comment by argiepiano** [comment] 2022-10-29 03:18
Yes, this approach may lead to a dead end. I see several problems, the most serious is the fact that nodes are served from the cached version, meaning that this approach will not work for different roles when viewing - you will view the one cached, unless you disable caching.

So, I'm thinking that perhaps this has to be filtered upon saving, rather than on rendering, meaning that, if a role with specific editing privileges tries to use a certain forbidden token, the token should be completely removed from the field before saving it (perhaps with a warning shown). What do you think?

**Comment by argiepiano** [comment] 2022-10-29 13:25
Having second thoughts about what I said above.

AFAIK filters always act on output. They are non-destructive. Removing a token from a text field upon saving goes against this. 

So, it seems to me that given the constraints put by entity cache (i.e. the inability to fulfill tokens dynamically when you are viewing a cached node), the idea of "tiering" the display by role will never work well unless you void caching.

The next best solution is then either:
1. Create a separate module that's not a filter, that removes unwanted tokens when saving a text field, OR
2. Ditch the idea of forbidding tokens based on role, and stick to forbidding them based only on the text format they are applied to (just like the Limit HTML tags filter)

**Comment by bugfolder** [comment] 2022-10-29 15:10
> 1. Create a separate module that's not a filter, that removes unwanted tokens when saving a text field

It would need to be applied recursively. `[node:[node:author]author]` would fool a single application. Also `<scr[node:author]ipt>...</scr[node:author]ipt>`-like shenanigans would have to be prevented.

But the whole idea of changing the user's text entry on save strikes me as problematic. (Editors, like CKEditor do this, of course, but to have a "Raw HTML" field do it seems wrong.)

> 2. Ditch the idea of forbidding tokens based on role, and stick to forbidding them based only on the text format they are applied to

This seems cleaner.

**Comment by bugfolder** [comment] 2023-01-02 17:15
Working on this. Here's the approach. When a text format uses the Token Filter filter, it would now have configuration settings for that particular format, which (currently) look like this:

![token_fliter_configuration](https://user-images.githubusercontent.com/29214084/210262025-37164b94-3d6e-4631-bee9-a43e2b84c5e8.jpg)

So you can either forbid or restrict to a specified set of tokens, using wildcards to define families of tokens.

**Comment by yorkshire-pudding** [comment] 2023-01-02 17:44
@bugfolder - I like this approach. Being able to choose whether to do by forbid or allow will make it simpler to do.  If there are just a few tokens to allow or forbid, then this will be easy to setup.

**Comment by bugfolder** [comment] 2023-01-02 19:58
A question for anyone: should the token specifications simply be strings with `*`wildcards, or full-fledged regexes?

I personally lean toward just using `*` wildcards as covering most cases (e.g., `[user:*]`, `[*:author:*]`) and being understandable and famiiar to more site architects doing the configuration. But I'd like to see if there are strong arguments for the additional power (albeit complexity) of regexes.

**Comment by yorkshire-pudding** [comment] 2023-01-02 20:02
Strings with wildcards please. Regex should not be required for site builder/architect

**Comment by bugfolder** [comment] 2023-01-03 03:13
> Strings with wildcards please. Regex should not be required for site builder/architect

Considering the hair-pulling I went through to try to get the regexes to work right, that's a good call! 😉

I've got a version working, in the PR. There's an update hook to initialize the new filter configuration settings on existing installs.

**Comment by yorkshire-pudding** [comment] 2023-01-04 09:52
I got this on the screen after I applied the patch:
![image](https://user-images.githubusercontent.com/20357797/210528631-365f1743-9a62-4571-9c49-992ad1a264b1.png)

I'm using PHP 8.0 on this test instance.

**Comment by yorkshire-pudding** [comment] 2023-01-04 10:09
Deleted previous message as I hadn't run database updates on installing.  I had to install manually as the HEAD doesn't match the latest release and therefore the patch wouldn't work against the released version.

**Comment by yorkshire-pudding** [comment] 2023-01-04 10:11
However, I still get this issue:
![chrome_qljhwzHZq7](https://user-images.githubusercontent.com/20357797/210532279-5788c660-1a4e-45f3-91c3-e14f3472ed5e.gif)

**Comment by yorkshire-pudding** [comment] 2023-01-04 12:28
Odd. I'm now getting the config screen. Might have been a caching issue.

**Comment by yorkshire-pudding** [comment] 2023-01-04 14:22
It doesn't seem to be working for forbid.  I've set forbid and entered:

```
user:*
site:*
```

In a page using that text format I've entered:
```
Test [user:name] on [site:name]
```

and this is what it looks like logged in:
![image](https://user-images.githubusercontent.com/20357797/210575211-2c413568-1e8f-4b97-916f-963129f3a3cb.png)

and not logged in:
![image](https://user-images.githubusercontent.com/20357797/210575422-05db6812-669c-4b33-a587-fa8199cd9e55.png)

I've tried clearing the cache but no joy. Am I missing something?

If I switch to allow with the same but then add another into the page, that should be disallowed, I get this:
![image](https://user-images.githubusercontent.com/20357797/210576636-2ef07775-039a-45f0-9111-e0d075aec6a8.png)

**Comment by bugfolder** [comment] 2023-01-04 14:59
> It doesn't seem to be working for forbid. I've set forbid and entered:
>
>`user:*`
>`site:*`

Try entering

`[user:*]`
`[site:*]`

I guess the help text should specify including the square brackets.

**Comment by yorkshire-pudding** [comment] 2023-01-04 15:04
Yes, that works thanks.  I can confirm that both allow and forbid work as expected.  However, if the user changes  settings, perhaps they need to be reminded to clear the relevant caches before they are reflected on existing content.

**Comment by bugfolder** [comment] 2023-01-04 15:18
Should we clear all caches for them after saving a change? Since text filters can be used just about anywhere, it would have to be fairly extensive cache-clearing. Or just warn them with a message?

Incidentally, I did run into one odd behavior. If I disable the filter, then save, then click the configure button and update, after closing the dialog, the text—but not the token tree link—vanishes. Can't figure out why, and it doesn't happen with any other filter.

**Comment by yorkshire-pudding** [comment] 2023-01-04 15:25
Yes, I noticed that behaviour but didn't think too much about it.
Tricky to know whether to clear the caches (as you say that could need to be all) as they may have just added the module and not have any embedded tokens yet.  Could be annoying if that was the case and it was a busy site, but on the other hand, it could cause a lot of frustration if it doesn't update. Perhaps just set a warning message that will give them enough information to know whether they need to clear them or not.

**Comment by bugfolder** [comment] 2023-01-04 20:32
I've added a warning message after saving a text format if there are changes in the "Replace Tokens" filter that could conceivably affect cached data.

I also changed the wording: instead of "allow" and "forbid," it's now "evaluate" and "ignore". (People can still use "forbidden" tokens; they just aren't evaluated.)

**Comment by yorkshire-pudding** [comment] 2023-01-04 21:07
Thanks @bugfolder - I think the help text is much clearer and the warning is both clear and helpful.
LGTM, WFM
👍

**Comment by yorkshire-pudding** [comment] 2023-01-18 18:01
@jenlampton and @argiepiano - do you have any further feedback on @bugfolder 's PR?  I think this is a very sensible and flexible approach.

**Comment by bugfolder** [comment] 2023-01-18 20:05
It occurs to me that "replace" might be a better term than "evaluate" in this usage, since "replace" seems to be used elsewhere with respect to tokens. (Updating the PR will be a bit delayed, I'm in NZ right now and, judging by connection speed, the internet sends packets via carrier kiwi.)

**Comment by yorkshire-pudding** [comment] 2023-01-18 20:14
> It occurs to me that "replace" might be a better term than "evaluate" in this usage, since "replace" seems to be used elsewhere with respect to tokens.

Makes sense

> the internet sends packets via carrier kiwi.)

I wonder if they conform to the [IPoAC ](https://en.wikipedia.org/wiki/IP_over_Avian_Carriers) network protocol?

**Comment by yorkshire-pudding** [comment] 2023-01-18 20:16
I see they consider kiwis in the "risks" section:

> The absence of viable local carriers. RFC6214: "In some locations, such as New Zealand, a significant proportion of carriers are only able to execute short [hops](https://en.wikipedia.org/wiki/Hop_(networking)), and only at times when the background level of photon emission is extremely low." This describes the flightless and nocturnal nature of [kiwis](https://en.wikipedia.org/wiki/Kiwi_(bird)).

**Comment by argiepiano** [comment] 2023-01-20 05:20
I've looked and tested - nice work here! The use of regex to match the wildcarded tokens is great.

I did leave a few comments - one of them regarding the update hook. Let me know if they make sense.

**Comment by argiepiano** [comment] 2023-01-20 13:48
I just reported a bug in the code that generates a notice - in the PR itself

**Comment by argiepiano** [comment] 2023-01-20 14:27
Actually, just kidding. I can't reproduce the notice, AND my suggestion was totally off -- one of those mornings :)

**Comment by yorkshire-pudding** [comment] 2023-10-18 11:20
@bugfolder @argiepiano @jenlampton - just reviving this to see if anything else needs doing or if it can now be merged. From comments it looks like everyone who tested it has found the PR works.

**Comment by bugfolder** [comment] 2023-10-18 17:26
OK by me.

**Comment by argiepiano** [comment] 2023-10-18 17:38
LGTM

**Comment by argiepiano** [comment] 2024-08-06 14:49
@yorkshire-pudding discovered an problem, outlined in the PR. It generates several warnings:
```
Warning: Undefined array key "replace" in _token_filter_filter_tokens() (line 74 of /Users/XXX/Sites/localhost/bdtesting/modules/token_filter/token_filter.module).

Warning: Undefined array key "tokens" in _token_filter_filter_tokens() (line 85 of /Users/XXX/Sites/localhost/bdtesting/modules/token_filter/token_filter.module).

Deprecated function: preg_quote(): Passing null to parameter #1 ($str) of type string is deprecated in _token_filter_filter_tokens() (line 85 of /Users/XXX/Sites/localhost/bdtesting/modules/token_filter/token_filter.module).
```

This is how to reproduce:
1. Start with a clean installation that has never had Token Filter installed (otherwise the json configuration for the text format will already contain some residual Token Filter settings)
2. Enable the token filter for a text format by checking the checkbox and saving, for example, here `admin/config/content/formats/filtered_html`
3. Do not edit the filter. Do not go to the Configure modal at all. 

Create a node with a token, e.g. [node:author], and view that node. 

The issue is that when token filter is first enabled, there are no settings at all. The portion of the text filter config file looks like this:
```json
        "filter_tokens": {
            "status": 1,
            "weight": 0,
            "module": "token_filter",
            "settings": []
        }
```

And normally that portion should look like this:

```json
        "filter_tokens": {
            "status": 1,
            "weight": 0,
            "settings": {
                "replace": "0",
                "tokens": ""
            },
            "module": "token_filter"
        }
```

I'm not sure if providing some defaults is possible, since the enabling/disabling is handled by core, which create the config portion. So perhaps some defensive coding is necessary in this case, @bugfolder .

**Comment by argiepiano** [comment] 2024-08-06 14:57
@bugfolder, oh, actually, this is as simple as providing `default settings` in the filter definition! See `filter_filter_info()`.

https://github.com/backdrop/backdrop/blob/96a0e03870c9fd09ab4134827a05148173e8e516/core/modules/filter/filter.module#L1946

**Closed as completed** 2024-08-31 19:31 UTC
